name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ANUJ_DOCKER }}
        password: ${{ secrets.ANUJ_DOCKER }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: anujahlawat411/ci-cd  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull anujahlawat411/ci-cd  # Replace with your Docker Hub username and repository
